### ISSUE TITLE
Comments while reading

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-group-exclusion-spec#5]
From a first quick look, this looks great. I really like the diagrams. A few things I noticed:

> In 4.1. Excluding a group member:
> and then publishes SSB message(s) encrypted to the remaining members

How are these posted? To what feeds? Probably add a: ... as explained in X

This is related to: "members have transitioned to the new epoch and ceased replication of the former group" in section 4 I think. Also somewhat contradicts 4.1.4 for the exclude message. So maybe rework that sentence to be: ... ceased replication of the former group as explained in section 4.1.

**Comment by staltz** [comment]
Thanks for taking a look!

This first paragraph in 4.1. is meant to just be an introduction to the section, not as rules. Maybe I should rephrase this intro paragraph so that no one understands it as being normative. The bullet list 4.1.x is normative.

> So maybe rework that sentence to be: ... ceased replication of the former group as explained in section 4.1.

I need to address the whole topic of replication (see #2 ) and I think I'll do it in a separate section. I think for these sections under 4.x I'll just specify how the next epoch is selected, but then I'll make another section on how to replicate the selected next epoch and what to do with the previous epochs.

**Comment by arj03** [comment]
Yeah, splitting out the replication seems like a good idea :)

**Comment by staltz** [comment]
Okay, I rephrased the intro inside 4.1. and the other topic is #2.

I'll close the issue just to have a more actionable TODO list, but feel free to comment more and give more feedback of course.
